# -*- coding: utf-8 -*-
# ~ Jesse K. Rubin ~ Pretty Useful Python
from typing import Any
from typing import Callable
from typing import Dict
from typing import Optional

def cash_it(funk: Callable): ...
def mkdirs(funk: Callable): ...
def dirdec(funk: Callable): ...
def flog(funk: Callable): ...
def in_n_out(funk: Callable): ...
def cprof(funk: Callable): ...

class tictoc(object):
    runs: Any = ...
    def __init__(self, runs: int = ...) -> None: ...
    args: Any = ...
    def __call__(self, time_funk: Callable, printing: bool = ...): ...
    @staticmethod
    def ftime(t1: float, t2: Optional[float] = ...): ...
