# -*- coding: utf-8 -*-
# ~ Jesse K. Rubin ~ Pretty Useful Python

from typing import Any
from typing import Iterable
from typing import List

from pupy._typing import Flint

def files_gen(dirpath: str=..., abs: bool=...) -> Any: ...
def dirs_gen(dirpath: str=..., abs: bool=...) -> Any: ...
def exhaust(it: Iterable[Any]) -> None: ...
def chunks(it: Any, chunk_size: Any): ...
def is_permutation(a: Any, b: Any): ...
def rotate(rlist: Any, rn: int = ..., left_rotate: bool = ...): ...
def rotations_gen(rlist: Any): ...
def digits_list(number: int) -> List[int]: ...
def int_from_digits(digits: Iterable[int]) -> int: ...
def iter_product(l: Iterable[int]) -> Flint: ...
