# -*- coding: utf-8 -*-
# ~ Jesse K. Rubin ~ Pretty Useful Python

from typing import Any

def bytes2str(bites: bytes, encoding: str=...) -> str: ...
def binary_string(number: int) -> str: ...
def string_score(strang: Any): ...
def is_palindrome(string: Any): ...
def strip_comments(string: Any): ...
def strip_ascii(s: Any): ...
def no_b(string: Any): ...
def no_u(string: Any): ...
def rhex_str(length: int=...) -> str: ...
