# -*- coding: utf-8 -*-
# ~ Jesse K. Rubin ~ Pretty Useful Python

from typing import Any

def binary_string(number: Any): ...
def string_score(strang: Any): ...
def is_palindrome(string: Any): ...
def strip_comments(string: Any): ...
def strip_ascii(s: Any): ...
def no_b(string: Any): ...
def no_u(string: Any): ...
def random_hex_str(length: int): ...
